# Generated by Django 5.2.1 on 2025-05-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orderitem_unit_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='kg', max_length=20),
        ),
    ]
