# Generated by Django 5.2.1 on 2025-05-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='address',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
